-- Provisional arrival grace: two hours after scheduled_end, matching the app
-- fallback. An unanswered check remains open indefinitely.
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS arrival_check_answer text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS arrival_check_resolved_end timestamptz;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS arrival_check_resolved_at timestamptz;
CREATE TABLE IF NOT EXISTS public.arrival_cases (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 work_order_id bigint NOT NULL REFERENCES public.work_orders(id),
 scheduled_end timestamptz NOT NULL,
 reported_by bigint NOT NULL,
 reported_at timestamptz NOT NULL DEFAULT now(),
 note text NOT NULL DEFAULT '',
 pro_response text,
 responded_at timestamptz,
 UNIQUE(work_order_id, scheduled_end)
);
ALTER TABLE public.arrival_cases ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.arrival_cases FROM anon, authenticated;
CREATE OR REPLACE FUNCTION public.resolve_arrival_check(p_work_order_id bigint, p_user_id bigint, p_action text, p_note text DEFAULT '')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE w public.work_orders%ROWTYPE; case_id bigint;
BEGIN
 SELECT * INTO w FROM public.work_orders WHERE id = p_work_order_id FOR UPDATE;
 IF NOT FOUND OR w.requester_user_id <> p_user_id THEN RAISE EXCEPTION 'not_your_order'; END IF;
 IF w.arrival_check_resolved_end = w.scheduled_end AND w.arrival_check_answer IS NOT NULL THEN
   IF w.arrival_check_answer <> p_action THEN RAISE EXCEPTION 'check_already_answered'; END IF;
   RETURN jsonb_build_object('ok',true,'newCase',false);
 END IF;
 IF w.scheduled_end IS NULL OR now() < w.scheduled_end + interval '2 hours'
 OR w.status IN ('completed','cancelled','customer_no_show','pro_no_show','disputed') THEN RAISE EXCEPTION 'not_arrival_check_eligible'; END IF;
 IF p_action NOT IN ('confirm_arrival','arrival_rescheduled','pro_no_show') THEN RAISE EXCEPTION 'invalid_action'; END IF;
 IF length(p_note) > 2000 THEN RAISE EXCEPTION 'note_too_long'; END IF;
 UPDATE public.work_orders SET arrival_check_answer = p_action,
  arrival_check_resolved_end = scheduled_end, arrival_check_resolved_at = now(),
  status = CASE WHEN p_action = 'pro_no_show' THEN 'pro_no_show' ELSE status END,
  updated_at = now() WHERE id = w.id;
 IF p_action = 'pro_no_show' THEN
  INSERT INTO public.arrival_cases(work_order_id,scheduled_end,reported_by,note)
  VALUES(w.id,w.scheduled_end,p_user_id,p_note) RETURNING id INTO case_id;
 END IF;
 RETURN jsonb_build_object('ok',true,'newCase',case_id IS NOT NULL,'caseId',case_id);
END $$;
REVOKE ALL ON FUNCTION public.resolve_arrival_check(bigint,bigint,text,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_arrival_check(bigint,bigint,text,text) TO service_role;
